#!/bin/bash

###
# Check for arguments
###
while getopts "u:p:o:n:" opt; do
	case $opt in
		u)
			user=$OPTARG
			;;

		p)
			passwd=$OPTARG
			;;

		o)
			oldName=$OPTARG
			;;

		n)
			newName=$OPTARG
			;;

		\?)
			echo "Invalid option: -$OPTARG" >&2
			;;
	esac
done

###
# If arguments aren't set
###
# Requeser user
if [ -z "$user" ];
then
	echo -n 'Please enter an admin user for the MariaDB/MySQL server: '
	read user
fi

# Request password
if [ -z "$passwd" ];
then
	echo -n "Please enter ${user}'s password: "
	read -s passwd
	echo ' '
fi

# Request old name
if [ -z "$oldName" ];
then
	echo -n 'Please enter the current name of the db: '
	read oldName
fi

# Request new name
if [ -z "$newName" ];
then
	echo -n 'Please enter the new name of the db: '
	read newName
fi

# Create the new DB
mysqladmin -u$user -p$passwd create $newName

# Copy the contents of the old DB to the new DB
mysqldump -u$user -p$passwd -v $oldName | mysql -uroot -p$passwd $newName

# Delete the old DB (will prompt for confirmation)
mysqladmin -u$user -p$passwd drop $oldName

# Success
echo "Done"